[LanguageProvider]
default_language = "en_GB"
supported_languages = ["cs_CZ", "en_GB"]

[ProcessingWidget]
inputPathEditPath = ""
outputPathEditPath = ""

[WorkflowSettings]
inputPathEditPath = ""
inputPathEditState = true
outputPathEditPath = ""
outputPathEditState = true
yearCheckboxState = true
monthCheckboxState = false
dayCheckboxState = false
subfoldersTypeCheckboxState = false
hiddenFoldersCheckboxState = false
fileNameEditState = true
filterCheckboxState = true
documentsFilesCheckboxState = true
txtFilesCheckboxState = true
officeFilesCheckboxState = true
imageFilesCheckboxState = true
musicFilesCheckboxState = true
archiveFilesCheckboxState = true
customExtensionsEditState = true
useTimestampCheckboxState = false
useCounterCheckboxState = false
deleteFileCheckboxState = true
showFailedFilesCheckboxState = true
defaultNameRadiobuttonState = true
userNameRadiobuttonState = false